### ISSUE TITLE
Xposed causes bootloops with some enabled modules

### ISSUE THREAD

**Issue by adrenogamer** [abforce/xposed_art_n#21]
I think its a common trouble for working modules because this module (XPrivacy) is works perfectly on any other Android version without support.
Found logcat in xposed installer data folder with FATAL errors in art. Last 4 strings is repeating later:
https://paste.debian.net/plain/984433

`09-04 04:33:50.706 I/Xposed  ( 7627): -----------------
09-04 04:33:50.706 I/Xposed  ( 7627): Starting Xposed version 88 (Xposed SDK25 Nougat ARM64 by PurifyOS), compiled for SDK 25
09-04 04:33:50.706 I/Xposed  ( 7627): Device: ASUS_Z00ED (asus), Android version 7.1.2 (SDK 25)
09-04 04:33:50.706 I/Xposed  ( 7627): ROM: lineage_Z00ED-userdebug 7.1.2 NJH47F 35412e2641 test-keys
09-04 04:33:50.706 I/Xposed  ( 7627): Build fingerprint: asus/lineage_Z00ED/Z00ED:7.1.2/NJH47F/35412e2641:userdebug/test-keys
09-04 04:33:50.706 I/Xposed  ( 7627): Platform: arm64-v8a, 64-bit binary, system server: yes
09-04 04:33:50.706 I/Xposed  ( 7627): SELinux enabled: yes, enforcing: no
09-04 04:33:57.780 I/Xposed  ( 7627): -----------------
09-04 04:33:57.780 I/Xposed  ( 7627): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-04 04:33:58.003 I/Xposed  ( 7627): Detected ART runtime
09-04 04:33:58.005 I/Xposed  ( 7627): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-04 04:33:58.331 I/Xposed  ( 7627): Loading modules from 
09-04 04:33:58.331 E/Xposed  ( 7627):   File does not exist
09-04 04:33:58.331 I/Xposed  ( 7627): Loading modules from /data/app/de.robv.android.xposed.mods.appsettings-1/base.apk
09-04 04:33:58.352 I/Xposed  ( 7627):   Loading class de.robv.android.xposed.mods.appsettings.XposedMod
09-04 04:33:58.375 E/Xposed  ( 7627): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:68)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:507)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:182)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:257)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.mods.appsettings.hooks.Activities.hookActivitySettings(Activities.java:49)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.mods.appsettings.XposedMod.initZygote(XposedMod.java:232)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:487)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:401)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:91)
09-04 04:33:58.375 E/Xposed  ( 7627): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.Class.classForName(Native Method)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.Class.forName(Class.java:400)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:66)
09-04 04:33:58.375 E/Xposed  ( 7627): 	... 8 more
09-04 04:33:58.375 E/Xposed  ( 7627): Caused by: java.lang.ClassNotFoundException: com.android.internal.policy.PhoneWindow.DecorView
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.Class.classForName(Native Method)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
09-04 04:33:58.375 E/Xposed  ( 7627): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-04 04:33:58.375 E/Xposed  ( 7627): 	... 12 more
09-04 04:33:58.375 E/Xposed  ( 7627): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
09-04 04:33:58.383 I/Xposed  ( 7627): Loading modules from 
09-04 04:33:58.383 E/Xposed  ( 7627):   File does not exist
09-04 04:33:58.384 I/Xposed  ( 7627): Loading modules from /data/app/biz.bokhorst.xprivacy-1/base.apk
09-04 04:33:58.410 I/Xposed  ( 7627):   Loading class biz.bokhorst.xprivacy.XPrivacy
09-04 04:34:00.971 F/art     ( 7890): art/runtime/gc/collector/mark_sweep.cc:415] Tried to mark 0xa1365310 not contained by any spaces
09-04 04:34:00.972 F/art     ( 7890): art/runtime/utils.cc:184] 12c00000-12e01000 rw-p 00000000 00:04 53794                              /dev/ashmem/dalvik-main space (deleted)
09-04 04:34:00.972 F/art     ( 7890): art/runtime/utils.cc:184] 12e01000-13201000 rw-p 00201000 00:04 53794                              /dev/ashmem/dalvik-main space (deleted)
09-04 04:34:00.972 F/art     ( 7890): art/runtime/utils.cc:184] 13201000-32c00000 ---p 00601000 00:04 53794                              /dev/ashmem/dalvik-main space (deleted)`

**Comment by abforce** [comment]
Did you apply [this commit](https://github.com/abforce/xposed_art_n/commit/94ba5a5ad759350d9d4af3f750552b8ed2ce6683)?
